services:
  wyoming_openai:
    image: ghcr.io/roryeckel/wyoming_openai:latest
    container_name: wyoming_openai
    ports:
      - "10300:10300"
    restart: unless-stopped
    environment:
      WYOMING_URI: tcp://0.0.0.0:10300
      WYOMING_LOG_LEVEL: INFO
      WYOMING_LANGUAGES: en
      TTS_OPENAI_URL: http://openai-edge-tts:5050/v1
      TTS_MODELS: "tts-1"
      TTS_BACKEND: "OPENAI"
      TTS_VOICES: "en-US-AnaNeural en-US-AndrewMultilingualNeural en-US-AndrewNeural en-US-AriaNeural en-US-AvaMultilingualNeural en-US-AvaNeural en-US-BrianMultilingualNeural en-US-BrianNeural en-US-ChristopherNeural en-US-EmmaMultilingualNeural en-US-EmmaNeural en-US-EricNeural en-US-GuyNeural en-US-JennyNeural en-US-MichelleNeural en-US-RogerNeural en-US-SteffanNeural"
      TTS_SPEED: "1.0"
    depends_on:
      openai-edge-tts:
        condition: service_healthy

  openai-edge-tts:
    image: travisvn/openai-edge-tts:latest
    container_name: openai-edge-tts
    restart: unless-stopped
    ports:
      - "5050:5050"
    environment:
      - PORT=5050
      - DEFAULT_SPEED=1.0
      - DEFAULT_LANGUAGE=en-US
      - REQUIRE_API_KEY=False
      - REMOVE_FILTER=False
      - EXPAND_API=False
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:5050/v1/models', timeout=5)"]
      interval: 30s
      retries: 3
      start_period: 40s