services:
  speaches:
    container_name: speaches
    image: ghcr.io/speaches-ai/speaches:0.9.0-rc.3-cpu
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      enable_ui: False
      log_level: info
      WHISPER__MODEL: Systran/faster-distil-whisper-large-v3
      WHISPER__compute_type: int8
      preload_models: '["Systran/faster-distil-whisper-large-v3", "speaches-ai/Kokoro-82M-v1.0-ONNX"]'
      SPEACHES_BASE_URL: http://speaches:8000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 5s
      retries: 12
      start_period: 60s
    volumes:
      - huggingface-hub:/home/ubuntu/.cache/huggingface/hub

volumes:
  huggingface-hub:
